apiVersion: apps/v1
kind: Deployment
metadata:
  name: Euouxe-frontend
  labels:
    app.kubernetes.io/part-of: Euouxe-AI
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9102"
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
      containers:
      - name: brim-ui
        image: brimnetwork/ui:3.4.0
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: brim-env
        resources:
          limits:
            memory: "512Mi"
            cpu: "0.5"
          requests:
            memory: "256Mi"
            cpu: "0.2"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 20
